services:
  frontend:
    build: ./frontend
    container_name: babysleep-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=/api
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: babysleep-backend
    volumes:
      - ./backend:/app
      - ./data:/app/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: babysleep-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  data:
